runners:
  - # Custom runner 1
    name: cirun-openstack-gpu
    labels:
      - linux
      - x64
      - self-hosted
      - cirun-openstack-gpu
    cloud: openstack
    instance_type: gpu_medium
    machine_image: ubuntu-2204-nvidia-docker-20221229
    region: RegionOne
