provider:
  win: azure
  osx: circle
  linux_aarch64: default
  linux_ppc64le: default
bot:
  automerge: true
  automerge_options:
    ignored_statuses:
      - linter
conda_forge_output_validation: true
