bot:
  automerge: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_ppc64le: travis
  linux_64: circle
  osx_64: azure
  win_64: azure
